/g4sbs/filename tout/simc_sbs4_1.root

/g4sbs/simcfile /w/halla-scshelf2102/sbs/pdbforce/SIMC/simc_gfortran/worksim/elastic_sbs4_1.root

## Configure Experiment
/g4sbs/exp             gmn

## Configure the target
/g4sbs/target          LH2
/g4sbs/targlen         15.0 cm           ## Target Length

## Configure generator settings
/g4sbs/kine            simc           ## Generator
/g4sbs/beamcur         1 muA
/g4sbs/rasterx         2.0 mm
/g4sbs/rastery         2.0 mm
/g4sbs/beamE           3.7278 GeV
/g4sbs/thmin           26.0 deg
/g4sbs/thmax           46.0 deg
/g4sbs/phmin          -30 deg
/g4sbs/phmax           30 deg

## Configure standard detector settings
/g4sbs/hcaldist        11.0 m
/g4sbs/hcalvoffset     0.45 m
/g4sbs/beamlineconfig  3                 ## set relevant beamline configuration
/g4sbs/sbsclampopt     3                 ## Front field clamp only
/g4sbs/uselead         0                 ## Lead turned off

## Configure the magnets
#/g4sbs/tosfield        BigBitePortableFieldMap.table 1
#/g4sbs/tosfield        SBSPortableFieldMap_FrontClampOnly_NoPoleShims.table 2
/g4sbs/bbfield         1
#/g4sbs/scalebbfield    1.077586
/g4sbs/scalebbfield    0.97
/g4sbs/48d48field      1
/g4sbs/sbsmagfield     0.82 tesla
/g4sbs/bbang           36.0 deg
/g4sbs/bbdist          1.7988 m
/g4sbs/sbsang          31.9 deg
/g4sbs/48D48dist       2.25 m

#/g4sbs/setbigbiteplate 1
#/g4sbs/bigbiteplatethick 0.3175 cm
#/g4sbs/bigbiteplatematerial Aluminum

## misc
/g4sbs/keepsdtrackinfo all true
/g4sbs/totalabs        true

/g4sbs/eventstatusevery 100
/g4sbs/run 100000
